const PROTEINS = [
  {
    name: "Gatorade protein bar (g)",
    flavor: "Chocolate Chip",
    calories: 190,
    proteins: 30,
    serving: 60,
  },
  {
    name: "Premier protein bar (g)",
    flavor: "Double chocolate crunch",
    calories: 270,
    proteins: 30,
    serving: 72,
  },
  {
    name: "Quest protein bar (g)",
    flavor: "Chocolate Chip Cookie Dough",
    calories: 190,
    proteins: 30,
    serving: 60,
  },
  {
    name: "BSN Protein Bars",
    flavor: "Chocolate Chip Cookie Dough (g)",
    calories: 230,
    proteins: 20,
    serving: 57,
  },
  {
    name: "MET-Rx Big 100 Colossal Protein Bars (g)",
    flavor: "Vanilla Caramel Churro",
    calories: 310,
    proteins: 32,
    serving: 85,
  },
  {
    name: "Isopure Infusions Whey Protein Isolate Powder (g)",
    flavor: "Tropical Punch",
    calories: 90,
    proteins: 20,
    serving: 25,
  },
  {
    name: "Pure Protein Powder (g)",
    flavor: "Vanilla Cream",
    calories: 160,
    proteins: 25,
    serving: 39,
  },
  {
    name: "Body Fortress Super Advanced Whey Protein Powder (g)",
    flavor: "Vanilla",
    calories: 200,
    proteins: 30,
    serving: 50,
  },
  {
    name: "BPI Sports Best Protein - 100% Whey Protein Blend (g)",
    flavor: "Chocolate Brownie",
    calories: 130,
    proteins: 24,
    serving: 34,
  },
  {
    name: "MuscleTech Phase 8 Protein Powder (g)",
    flavor: "Vanilla",
    calories: 150,
    proteins: 26,
    serving: 42,
  },
  {
    name: "Fairlife Core Power Elite High Protein Shake (ml)",
    flavor: "Double Rich Chocolate",
    calories: 230,
    proteins: 42,
    serving: 414,
  },
  {
    name: "Ensure Max Protein Nutrition Shake (ml)",
    flavor: "Milk Chocolate",
    calories: 150,
    proteins: 30,
    serving: 330,
  },
  {
    name: "Quest Nutrition Ready to Drink Salted Caramel Protein Shake (ml)",
    flavor: "Caramel",
    calories: 160,
    proteins: 30,
    serving: 325,
  },
  {
    name: "Pure Protein Complete Ready to Drink Shakes (ml)",
    flavor: "High Protein Rich Chocolate",
    calories: 140,
    proteins: 30,
    serving: 325,
  },
  {
    name: "Muscle Milk Genuine Protein Shake (ml)",
    flavor: "Chocolate",
    calories: 160,
    proteins: 25,
    serving: 330,
  },
  {
    name: "Premier Protein 30g Protein Shake (ml)",
    flavor: "Chocolate",
    calories: 160,
    proteins: 30,
    serving: 340,
  },
];
